### ISSUE TITLE
Missing iOS files

### ISSUE THREAD

**Issue by profmike** [ARDroneSDK3/Samples#1]
The following are referenced in the iOS sample, but aren't found in the SDK frameworks nor in the sample files:
ARStreamManager
ARThread
ARFrame
ARUtils/ARUtils.h

**Comment by dmileff** [comment]
THE SAMPLES DO NOT WORK ON IOS.  As stated 25 days ago. there are missing files. plain and simple.
I've been working on this for awhile and have just plain given up for the meantime.  Would be VERY beneficial to just send along the missing files.  Trying to reverse engineer something that should already be compilable is a big waste of time.  If someone has this working PLEASE send along details ;) .  Also ,  Including code in this repository with missing .h files is just wrong, and is going to make a lot of people more frustrated.  Better to just pull down/remove the samples   ... since they obviously do not work.   
--don

**Comment by GOPINATH-GS4** [comment]
Nicolos, No issues in compiling the 
https://github.com/ARDroneSDK3/ARSDKBuildUtils
The works fine, the issue I am facing is with the IOS samples, which has missing files, I will wait for you to upload the working example 
-- GOPI

**Comment by stanley0925** [comment]
Agree with Mike,

Can you please provide us a completed simple "Hello World" project that just does 
1) Connect to Device, 
2) Take off, 
3)Moving up, down,left,right
4) Land, 
5) Disconnect.

Really looking forward on your reply.
thank you.

--STAN

**Comment by VictorVarLed** [comment]
I have experienced the same issues. 
Downloaded and installed the SDK, created a new Xcode project, added the libraries and the sample files and ...
'ARUtils/JumpingSumoDeviceController.h' file not found :(

Please, include a full working example ASAP!
Thanks

**Comment by weaversa** [comment]
The new `JumpingSumo` example compiled and ran fine for me just using the command prompt and following the instructions in the README.

**Comment by djavan-bertrand** [comment]
Hi everybody, 

Working samples are now provided. They are basics but show you how to handle a specific job.
From this examples and from the docs, I'm pretty sure you can achieve the tasks you want with the drones.

If you have problems running these working samples, please open an issue.
Thanks

**Comment by dmileff** [comment]
As stated previously many times. IOS sample build does NOT work. Yes, Unix does work, however, IOS does not. There are missing files when compiling any of the JumpingSumoDeviceController... IOS  files.

These files are MISSING:
#import <ARUtils/JumpingSumoDeviceController.h>
#import <ARUtils/JumpingSumoARNetworkConfig.h>

**Comment by dmileff** [comment]
ARUtils/JumpingSumoDeviceController.h
ARUtils/JumpingSumoARNetworkConfig.h

**Comment by ARDroneSDK3User** [comment]
Hello dmileff,

Please take a little time to read the README, it is well stated inside that the files you are trying to compile are NOT runnable. These are not sample applications, but sample files that should help you to write your own application. A sample application under linux is also provided.
The sample files are extracted from the official Parrot application called Freeflight 3. Freeflight 3 is a proprietary closed source but free application. I'm sure you understand that we cannot provide source code of this application.
As a user, feel free to download install and use Freeflight 3 on iOS or Android.
As a developer, feel free to develop any application you want using provided sample under linux and sample files which give information for all drones. We will give full support if you need information or encounter some issues in developing your own application.
Of course, like any other open source project, feel free to contribute and we will host your own samples to increase the variety of samples for the community. We will also provide eventually new runnable sample applications controlling various drones on various platform.  

We will NOT provide missing files for iOS and Android as those missing files are part of the closed source application.

I hope that help to clarify why it does not compile and how to use those files.

Best Regards,
Parrot SDK Team

**Comment by gopi-koneksahealth** [comment]
Dear Parrot SDK team,

Everybody understands that those samples won't compile and missing files,
you really think putting those files there adds any value? I used one of
those samples as example and reverse engineered creating the missing
variables and successfully compiled, guess what? I am not able to make it
work, I am sure I am doing something wrong

My point is those files add NO VALUE for many developers like me, why can't
you do us a favor and take those down and just leave the working examples

I also think that is a good practice, when you are making some of your code
available for general development community you keep it simple and
straightforward, I hope you understand our frustration

regards
Gopi

**Comment by darryljackman** [comment]
You guys provided "non-compatible" files!!!!

WTF!!!

You guys just continue to take the cake, and you just keep telling us people that the samples are intentionally non-functional, ok fine, then where the f**k are the functional ones/why the f**k didn't you include some functional ones??

It only shows us that you guys have no problems releasing partial/broken/unusable material, which is also evidenced by the shoty FreeFlight and Bebop Firmware releases which always have many broken things, so I guess my fault is putting faith in Parrot for actually being able to pull this off.

I downloaded and installed the Leap Motion SDK, and within minutes i had a running program collecting all the input data, running it through call backs for processing.. MINUTES!!!

I've been almost 2 MONTHS picking at this, and soon as I get a couple minutes in, I get so frustrated at the shittiness!!

I've NEVER EVER SEEN SUCH CARP in an SDK in MY LIFE!!!

So GOD DAMN FRUSTRATING, makes me hate Parrot!!

**Comment by GOPINATH-GS4** [comment]
I gave up on this, these guys are totally unresponsive, I am not campaigning or anything, but I switched to 3DR IRIS, of course it is extra couple of hundred dollars + Camera and gimbal extra, but it is awesome and not a toy like this one 

I gave my PARROT to my nephew and he crashed it within couple of hours, DAMN it felt good
