### ISSUE TITLE
RollingSpiderPiloting reconnect issue

### ISSUE THREAD

**Issue by weaversa** [ARDroneSDK3/Samples#10]
I had a consistent problem w/ this new sample where the drone would connect fine directly after a reboot, but would not reconnect on subsequent attempts.

I was able to fix this problem by sending the date and time over to the drone (as was done in the free flight 3 extracted code). You can see the fix I applied here: https://github.com/weaversa/Samples/blob/master/Contributions/OSX/RollingSpiderOK/DeviceController.m

I wanted to document this in case others were having the issue as well.

**Comment by djavan-bertrand** [comment]
Hi weaversa, 
Thanks again for this issue. It has been notified to the Rolling Spider firmware team.

You were right by saying that sending date and time fix this issue. We will update our sample soon.

Best regards, 
Djavan
