### ISSUE TITLE
Bebop and Jumping Sumo video streaming slowing to 1 frame per second during piloting

### ISSUE THREAD

**Issue by timsee** [ARDroneSDK3/Samples#11]
I've been working on an app that will use the Bebop and Jumping Sumo on iOS. So far I'm able to connect and control the robots. I can also receive packets from the robot, and immediately after connection, I have a video stream. I used a combination of the JumpingSumo Unix examples and the non-runnable iOS samples to get to this point. 

However, I run into a strange issue when I start sending piloting commands. After a few commands, the video stream drops down to 1 frame per second. If a few more commands are sent, it stops sending the video packets all together. This problem has identical behavior for both the Jumping Sumo and Bebop.

I've also noticed that when I tried to send the mediaStreamingVIdeoEnable command with its flag set to 1, I get a callback telling me that the media streaming is disabled. I'll even get this callback when I'm simultaneously getting the video stream.

If I connect to the parrot app afterwards, they are able to pick up the video, so I think its probably an issue with my configuration parameters or I need to do something to keep the stream alive after I start moving the robot around. 

Anyone experiencing similar problems or have any advice?

**Comment by N-Bz** [comment]
Hi,

This a "normal" behavior of the Bebop Drone : we use the regularity of the piloting commands in our wifi quality estimator.

To keep the "good" video, you'll need to send the piloting commands in a periodic manner (we send the value every 50ms on the JumpingSumo and every 25ms, but the important thing is that your period should not vary over time).

Regards,
Nicolas BRÛLEZ

**Comment by timsee** [comment]
Hey,

Thanks! I added regular commands and it fixed things immediately for both the Bebop and the Sumo. 

~Tim
