### ISSUE TITLE
Detecting color of rolling spider

### ISSUE THREAD

**Issue by profmike** [ARDroneSDK3/Samples#13]
What's the best way in the SDK to detect the color (white/blue/red) of the rolling spider drones? It seems that the device names could be renamed. 

Thanks in advance.

**Comment by djavan-bertrand** [comment]
Hi, 
You can get the color from the product serial (the high part of it). 
You can get it through the callback passed to ARCOMMANDS_Decoder_SetCommonSettingsStateProductSerialHighChangedCallback.
The serial should be PIXXX319Y, PIXXX320Y or PIXXX321Y (where X and Y are characters).
319 = white.
320 = blue.
321 = red.

Regards,
Djavan
