### ISSUE TITLE
Rolling Spider Piloting Sample - iOS 8 & 64Bit Architecture

### ISSUE THREAD

**Issue by stephen-squidink** [ARDroneSDK3/Samples#16]
This sample works really well and I have hooked it up with a BLE MadCatz game controller for iOS, video [here] (https://www.youtube.com/watch?v=fEFMLOLL3Vg). 

The issue I am having is getting this to work on a iPhone 6 with iOS 8, the game controller doesn't seem to work with the OS that is running with 64 bit architecture, I keep getting this constant warning. 
```
Warning - conversion from 64 bit to 32 bit integral value requested within NSPortCoder, but the 64 bit value 15714370154650875141 cannot be represented by a 32 bit value
```
I decide to update the App to compile with the 64bit architecture, then I get a load of errors from your framework and library so, I wondered if you are planning to release a version of the Sample app or SDK that supports 64 bit architecture?

Also, with Apple stating that everything should be built with 64 bit architectures I think it will be a good idea to just support it and a lot of people are requesting I release this App, because it makes the Rolling Spider a lot more fun when you have a physical controller, but I can't do that without the 64 bit support.

Thanks.

**Comment by timsee** [comment]
I am also concerned about this, as we are unable to submit any apps to the app store due to it:

https://developer.apple.com/news/?id=10202014a


The workaround you can use during development it is to change your Build Settings Architecture from:

$(ARCHS_STANDARD)

to

$(ARCHS_STANDARD_32_BIT)

This probably won't make it through the app store submission process though, since it goes directly against apple's requests as of February 1, 2015.

**Comment by N-Bz** [comment]
Hi,

We also have the same issue for FreeFlight, so we're working on it (and we actually already did some commits on ARSDKBuildUtils regarding the mixed 32/64 bits builds for libcurl).

Our ETA for the 64 bits build feature is "at the end of next week" (March 6) for internal builds, and hopefully the same day for the public SDK ;)

(And BTW, we will probably also enable arm64 build for Android too)

Regards,

**Comment by N-Bz** [comment]
Hi,

The SDK has been updated to support 64 bits iOS builds.
The Sample applications will be upgraded to support 64 bits "asap" (no ETA on this, sorry ;))

Regards,
Nicolas.

**Comment by timsee** [comment]
Awesome,

Dropping the 64-bit iOS builds and changing the build architecture back to:

$(ARCHS_STANDARD)

made it work on first try :) 

Thanks!

~Tim
