### ISSUE TITLE
Commands getting dropped due to "Insufficient free space in the buffer"

### ISSUE THREAD

**Issue by timsee** [ARDroneSDK3/Samples#18]
Hey,

We've made pretty substantial progress on our iOS based controller for Bebop and Sumo but we've been running into one issue that leads to the dropping of a lot of commands.

We are sending a new piloting command every 50 milliseconds for the Sumo and every 25 milliseconds for the Bebop as is suggested here: https://github.com/ARDroneSDK3/Samples/issues/11

It seems that sometimes, particularly on the sumo, we start to get a ton of warnings that say:

 ARNETWORK_Manager_SendData() failed. Insufficient free space in the buffer

These warnings will persist for a few seconds and everything will lag. This is also a much more common problem when we test in areas with a lot of wifi activity, which is understandable. It also seems to happen most frequently immediately after connection to the robot. 

Is there any good way to recover from this situation other than just waiting it out for the robot to correct it itself?

Thanks!

**Comment by N-Bz** [comment]
Basically, these messages are the consequences of the network lag, not the source ;)

You can safely ignore them for non-acknowledged commands (like the piloting commands).

Regards,

**Comment by timsee** [comment]
Awesome,

Yeah,  we had figured they were a direct result of network lag and there was no way around it. We just wanted to make sure we weren't wrong :)

Thanks again!

~Tim
