### ISSUE TITLE
Corrupt libraries on Rolling Spider Android app sample

### ISSUE THREAD

**Issue by AleAntunez** [ARDroneSDK3/Samples#19]
Jar files attached to the proyect are corrupt and cannot be built with Android Studio.

**Comment by djavan-bertrand** [comment]
Hi AleAntunez, 

Have you built the SDK by running the command ./SDK3Build.py -t Android ? See [this link](https://github.com/ARDroneSDK3/Docs/blob/master/Installation/INSTALL) for more information on how to build the SDK. 
Did you let the project in its original location ?

Regards, 
Djavan
