### ISSUE TITLE
Sample codes of Rolling Spider for OSX(Unix)

### ISSUE THREAD

**Issue by Hzikajr** [ARDroneSDK3/Samples#2]
Dear all,

Is there any example to 1:connect, 2:disconnect, 3:send commands to Rolling Spider from OSX or Unix machine?
I'm looking forward to hearing from you,

**Comment by weaversa** [comment]
I'm doubtful it will happen because of a comment found here:
https://github.com/ARDroneSDK3/Docs/blob/master/SDK/iOS/libARNetworkAL/html/index.html

It reads:
```
BLE Network: BLE Network type is not available on all platforms (currently only available on iOS). It uses Bluetooth 4.0 (Bluetooth Low Energy), which is used on some ARSDK products
```
And, the Rolling Spider relies on BLE. Though, I'd love to be proven wrong!

**Comment by Tycale** [comment]
New macbook comes with BLE. I think it should be possible.. But I have no clues how.

**Comment by Hzikajr** [comment]
Thank you for your reply, @weaversa and @Tycale,

Hmm... actually, the CoreBluetooth.framework in iOS SDK and OSX SDK are little bit different.
So all sources should be working on the iOS platform, right?
Anyway, the iOS example codes are not describing how to control a drone.
Do you have any idea on that? Which functions enables to control the rolling spider?
(e.g. MiniDroneController::initWithService(ARService)-> <next> ->)

Cheers,

**Comment by weaversa** [comment]
I found a partial Xcode project in the SDK that gives some hints. Specifically, `libARUtils/TestBench/iOS/TestBLEFtp/TestBLEFtp/autoTest.m`

I paired it down, just trying to simply discover my Rolling Spider (code and makefile below). But, I can't get it to work. The most obvious problem is that `centralManagerDidUpdateState` from `ARDISCOVERY_BonjourDiscovery.m` is not being called. I don't really know much about BLE, so maybe someone else can fix what I have?

You can find your drone name (ex. `RS_B012345`) in the `fvt6.txt` file, on the mounted drive that appears after plugging the drone into my computer via USB.

`test.m`
```
#import <Foundation/Foundation.h>
#import <libARDiscovery/ARDISCOVERY_BonjourDiscovery.h>

int main() {
  ARBLEService *foundService = nil;

  [[ARDiscovery sharedInstance] start];

  while (foundService == nil) {
    [NSThread sleepForTimeInterval:1];
    for (ARService *obj in [[ARDiscovery sharedInstance] getCurrentListOfDevicesServices]) {
      fprintf(stderr, "\nFound Something!\n");
      if ([obj.service isKindOfClass:[ARBLEService class]]) {
        ARBLEService *serviceIdx = (ARBLEService *)obj.service;
        NSLog(@"%@", serviceIdx.peripheral.name);
        NSString *NAME = @"RS_B012345";
        if ([serviceIdx.peripheral.name isEqualToString:NAME]) {
          fprintf(stderr, "\nFound My Drone!\n");
          NSLog(@"%@", serviceIdx.peripheral);
          foundService = serviceIdx;
          break;
        }
      }
    }
  }

  [[ARDiscovery sharedInstance] stop];
}
```
`Makefile`
```
LIBAR=$(HOME)/local/packages/libAR/ARSDKBuildUtils/Targets/Unix/Install

FRAMEWORKS=-framework Foundation
INCLUDES=-I$(LIBAR)/include
LIBDIR=-L$(LIBAR)/lib
LIBS=-lardiscovery

test: test.m Makefile
        clang $(LIBDIR) $(INCLUDES) $(LIBS) $(FRAMEWORKS) $< -o $@

clean:
        rm -rf test
```
Sample run
```
$ make 
clang -L$(HOME)/local/packages/libAR/ARSDKBuildUtils/Targets/Unix/Install/lib -I$(HOME)/local/packages/libAR/ARSDKBuildUtils/Targets/Unix/Install/include -lardiscovery -framework Foundation test.m -o test
$ ./test
2015-01-17 11:15:03.948 test[26728:6257305] -[ARDiscovery start]:278
^C
$
```

**Comment by weaversa** [comment]
I finally figured out a way to discover a Rolling Spider.

```
#import <Foundation/Foundation.h>
#import <libARDiscovery/ARDISCOVERY_BonjourDiscovery.h>

void discover_drone() {
  ARBLEService *foundService = nil;
  ARDiscovery *ARD = [ARDiscovery sharedInstance];

  while(foundService == nil) {
    [NSThread sleepForTimeInterval:1];
    for (ARService *obj in [ARD getCurrentListOfDevicesServices]) {
      fprintf(stderr, "\nFound Something!\n");
      if ([obj.service isKindOfClass:[ARBLEService class]]) {
        ARBLEService *serviceIdx = (ARBLEService *)obj.service;
        NSLog(@"%@", serviceIdx.peripheral.name);
        NSString *NAME = @"RS_B012345";
        if ([serviceIdx.peripheral.name isEqualToString:NAME]) {
          fprintf(stderr, "\nFound My Drone!\n");
          NSLog(@"%@", serviceIdx.peripheral);
          foundService = serviceIdx;
          break;
        }
      }
    }
  }

  [ARD stop];
  exit(0);
}

int main() {
  @autoreleasepool {
    long long seconds_to_discover = 10;
    ARDiscovery *ARD = [ARDiscovery sharedInstance];
    [ARD start];

    dispatch_queue_t my_main_thread = dispatch_queue_create("MyMainThread", NULL);
    dispatch_async(my_main_thread, ^{ discover_drone(); });
    
    [[NSRunLoop currentRunLoop] run];//  dispatch_main();
  }
  return 0;
}
```

```
2015-01-21 12:21:53.540 test[40925:7101356] -[ARDiscovery start]:278
2015-01-21 12:21:53.545 test[40925:7101356] New CBCentralManager state : CBCentralManagerStatePoweredOn
2015-01-21 12:21:53.545 test[40925:7101356] -[ARDiscovery start]:278
2015-01-21 12:21:55.076 test[40925:7101356] New device RS_B012345

Found Something!
2015-01-21 12:21:55.554 test[40925:7101360] RS_B012345

Found My Drone!
2015-01-21 12:21:55.555 test[40925:7101360] <CBPeripheral: 0x7feb31e00b00 identifier = UUID, Name = "RS_B012345", state = disconnected>
2015-01-21 12:21:55.555 test[40925:7101360] -[ARDiscovery stop]:328
```

**Comment by weaversa** [comment]
I was able to create a sample project that makes use of the above as well as the iOS MiniDrone sample code to discover, connect to, and send commands to a Rolling Spider drone solely from the command prompt. If anyone wants what I have so far, feel free to message me.

**Comment by N-Bz** [comment]
And if you want it to be integrated as a sample (with all due credits to the author, of course), feel free to make a pull request ;)

**Comment by Tycale** [comment]
I would be interested in the code for running Parrot Spider via Mac os X (xcode).
Can you send me everything needed to try it myself ?

Also, I think that you should try to do a pull-request on github. A lot of people might be interested. 

Thanks in advance
(You can contact me via mail via github(-at-)tycale.be)

**Comment by Hzikajr** [comment]
Hi @weaversa ,

I really interested in your project, so could you send me the sample project file?
Ml: ryo<at>imaginaryshort.com
I'd appreciated it if you send me the file!

**Comment by Tycale** [comment]
You can try it from the repo of @weaversa. He also did a pull-request :)

I tried and it worked :) Nice job :+1: 

I had to change the line NSString *NAME = @"RS_B"; to make it works. My parrot spider prefix name is "RS_R".

**Comment by weaversa** [comment]
Oh the things I do not know...I guess the prefix could be shortened to just "RS_". But, there is likely some better way to identify the drone than this name.

**Comment by Tycale** [comment]
A better way should be to check prefix the MAC address prefixes.

It seems that Parrot uses theses prefixes : 
* 00121C
* 00267E
* 9003B7
* A0143D

**Comment by djavan-bertrand** [comment]
In fact you don't have to check the MAC address, neither the name (except if you have multiple Rolling Spiders and you only want to connect to a specific one). If the service of the ARService is an instance of the ARBLEService class, or (better) if the product of the ARService is a ARDISCOVERY_PRODUCT_MINIDRONE, the ARService is a RollingSpider service.

Also, instead of querying each second the current list of devices services, you can observe the notification which is posted each time the list is updated. The name of the notification is *kARDiscoveryNotificationServicesDevicesListUpdated* .

By the way, thank you weaversa for your sample ! 

Best regards, 
Djavan

**Comment by stephen-squidink** [comment]
May I ask how you set this up in your Xcode project? I have ran the ARUtils to build the libs for Unix and imported all the .dylib and .a files into Xcode, then I imported all the .h header files, e.g. ARSAL.h. I have then added the RSLib files and then changed the main.m code to use your RollingSpiderTest.m code. 

I have it compiling and running. It connects to my Rolling Spider Drone, it then runs the Services and gets to this point.

```
2015-01-23 12:20:52.655 test[23757:160b] ==REGISTERED Characteristic : fd23, 36380
2015-01-23 12:20:52.677 test[23757:160b] ==REGISTERED Characteristic : fd53, 36fa0
2015-01-23 12:20:52.678 test[23757:160b] Initialized ARNetwork
```

Then it throws this error below.

```
2015-01-23 12:20:52.756 virtue[23757:303] -[CBUUID UUIDString]: unrecognized selector sent to instance 0x6100000365e0
2015-01-23 12:20:52.757 virtue[23757:303] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CBUUID UUIDString]: unrecognized selector sent to instance 0x6100000365e0'
```

Have any idea what might be causing this? Have I missed a lib or framework?

Thanks

**Comment by weaversa** [comment]
<<May I ask how you set this up in your Xcode project?>>
I'm not going to be much help here because, honestly, I've never used Xcode, only emacs, Makefiles, and the command prompt. About the code --- I just monkeyed around with everything until it worked for me. Sounds like you'll have to do a bit of the same. Though, I'm sure others will appreciate the work you put into it if you manage to get it up and running with Xcode.

**Comment by djavan-bertrand** [comment]
Hello, 

We've tried to run it with xCode. We managed to get it work the following way (which is maybe not the best way ;) ) : 
Import sources from the sample.
Import .h files from ARSDKBuildUtils/Target/Unix/Install/include
Import .dylib files from ARSDKBuildUtils/Target/Unix/Install/bin
In your target, Build Settings, in Apple LLVM Custom compiler flags, in Other C Flags, add : 
- -L YOUR_SDK/Target/Unix/Install/bin
- -I YOUR_SDK/Target/Unix/Install/include
- -lardiscovery -larnetworkal -larsal -larnetwork -larcommands

And in Build Phases add in Link Binary With Libraries the framework Core Bluetooth.

I'm not sure it will fix your problem. Do you have other logs that warns you about something before the crash ?

Regards, 
Djavan

**Comment by stephen-squidink** [comment]
That sounds like the same steps I have done, added the Other C Flags just now, but seem to be getting the same issue. Also, how come your going to the bin folder in Install, my bin folder has curl and curl-config files. The .dylib files are in Install/lib.

I did some debugging and I end up at a wait function before it throws the exception in the MiniDroneDeviceController.m line 513.

```
[_initialSettingsReceivedCondition wait];
```

This is where it throws the exception.  

Djavan, do you have a sample Xcode project you could share so i can have a look at what I could be doing wrong. 

Thanks, much appreciated.

**Comment by Hzikajr** [comment]
Dear all,

How to can I change posture of a rolling spider?
I used some commands like `userRollChanged:(float)roll` or `userYawChanged:(float)yaw` to control posture, but it seems that a rolling spider didn't change its posture.

I used commands like as follows:
`[MDDC userRollChanged:10.0];
[NSThread sleepForTimeInterval:3];
[MDDC userRollChanged:30.0];
[NSThread sleepForTimeInterval:3];`

do you have any example to control the rolling spider's posture?

Thanks in advance,

**Comment by weaversa** [comment]
I have done it, but needed to change a few things --- hack/smash. I commented out a bunch of lines in the controllerLoop function. This is not the right way to do it (I earlier commented out all of the ARThread stuff that would make this work correctly), but it does work as an initial hack.

```
- (void)controllerLoop
{
    eDEVICE_CONTROLLER_STATE currentState;
    MiniDroneData_t localState;
    BOOL isRunning = NO;

    [_stateLock lock];
    currentState = _state;
    isRunning = !_isInPause;
    [_stateLock unlock];

    if (isRunning)
    {
      //switch(currentState)                                                                                                                                 
      //{                                                                                                                                                    
      //case DEVICE_CONTROLLER_STATE_STARTED:                                                                                                                
                // Make a copy of the drone state.                                                                                                           
                [_droneStateLock lock];
                localState = _droneState;
                [_droneStateLock unlock];
                /*NSLog(@"====> %d, %d, %d, %d, %d, %f", (uint8_t)(localState.pilotingData.active ? 1 : 0),                                                  
                 (int8_t)(localState.pilotingData.roll * 100.f),                                                                                             
                 (int8_t)(localState.pilotingData.pitch * 100.f),                                                                                            
                 (int8_t)(localState.pilotingData.yaw * 100.f),                                                                                              
                 (int8_t)(localState.pilotingData.gaz * 100.f),                                                                                              
                 localState.pilotingData.heading);*/
                [self MiniDroneDeviceController_SendPilotingPCMD:[MiniDroneARNetworkConfig c2dNackId] withSendPolicy:ARNETWORK_SEND_POLICY_DROP withCompleti\
onBlock:nil withFlag:(uint8_t)(localState.pilotingData.active ? 1 : 0) withRoll:(int8_t)(localState.pilotingData.roll * 100.f) withPitch:(int8_t)(localState\
.pilotingData.pitch * 100.f) withYaw:(int8_t)(localState.pilotingData.yaw * 100.f) withGaz:(int8_t)(localState.pilotingData.gaz * 100.f) withPsi:localState.\
pilotingData.heading];
                //break;                                                                                                                                     

                //case DEVICE_CONTROLLER_STATE_STOPPING:                                                                                                     
                //case DEVICE_CONTROLLER_STATE_STARTING:                                                                                                     
                //case DEVICE_CONTROLLER_STATE_STOPPED:                                                                                                      
                //default:                                                                                                                                   
                // DO NOT SEND DATA                                                                                                                          
                //break;                                                                                                                                     
                //}                                                                                                                                          
    }
}
```

Then:

```
  [MDDC start];
  [NSThread sleepForTimeInterval:5];
  NSLog(@"MDDC Started");

  [MDDC userRequestedSpeedSettingsMaxRotationSpeed:10.0];
  [NSThread sleepForTimeInterval:1];

  [MDDC userRequestedFlatTrim];
  [NSThread sleepForTimeInterval:1];

  NSLog(@"Blink Blink");
  [MDDC userRequestSetAutoTakeOffMode:1];
  [NSThread sleepForTimeInterval:4];

  int i;
  for(i = 0; i < 3; i++) {
    [MDDC userYawChanged:0.75];
    [MDDC controllerLoop];
    [NSThread sleepForTimeInterval:0.1];
  }

  [NSThread sleepForTimeInterval:2];                                                                                                                 

  [MDDC userRequestedLanding];
  [NSThread sleepForTimeInterval:2];

  [MDDC stop];
  [NSThread sleepForTimeInterval:5];
```

**Comment by weaversa** [comment]
Also --- always request a flat trim before taking off! Otherwise, the drone seems to remember it's last settings (from a previous crash) and could freak out after takeoff. I cut my thumb on a propellor because of this :-1:

It would be nice to have a table (from the developers) giving the ranges for commands. For example, what does `userYawChanged` range over? What are the `min` and `max` for each value...`min <= userYawChanged <= max`? Maybe it already exists somewhere?

**Comment by djavan-bertrand** [comment]
Hi, 
These bounds are specified in the docs (Unix->libARCommands-> ARCOMMANDS_Generator_GenerateMiniDronePilotingPCMD).
The bounds of roll, pitch, yaw gaz are from -100 to 100 and the flag is a boolean needed to activate roll/pitch movement.

But on the code you use, the *controllerLoop* changes the values roll/pitch/yaw/gaz by multiplying them by 100. So the values passed to userYawChanged, userGazChanged (...) should be a float between -1 and 1.

Best regards, 
Djavan

**Comment by weaversa** [comment]
Thanks!

I also found some information here http://www.robotappstore.com/Knowledge-Base/How-to-Control-ARDrone-Movements-During-Flight/99.html
It verifies my thought that `userRequestedFlatTrim` should always be issued before takeoff.

One more question --- what can `Psi` / `userHeadingChanged` be used for?

**Comment by djavan-bertrand** [comment]
Hi, 

The psi value is not used for the moment by the drones. I will update the command comments to make it clear.
Thanks,
Djavan

**Comment by sethyx** [comment]
Hi All,

I have an unfinished Python library to control Rolling Spiders - https://github.com/sethyx/py-minidrone
I didn't really want to publish it until it's ready (it was private until now), but considering the lack of time I can spend on it nowadays, and the fact that I've just found this thread, here you go.

I hope some of you will find it useful.
