### ISSUE TITLE
BebopPiloting ?

### ISSUE THREAD

**Issue by astrodomi** [ARDroneSDK3/Samples#21]
when we can expect a version of BebopPiloting for iOS ?? ...like RollingSpiderPiloting

**Comment by CesarRN** [comment]
I hope it ...

**Comment by djavan-bertrand** [comment]
You now have access to a sample to [pilot the Bebop drone on iOS](https://github.com/ARDroneSDK3/Samples/tree/master/iOS/BebopDronePiloting) :)

You just have to update ARSDKBuildUtils, build it for iOS and you will be able to launch the XCode project which is in Samples/iOS/BebopDronePiloting/ .
