### ISSUE TITLE
What is "DeviceControllerCompletionBlock" ?

### ISSUE THREAD

**Issue by CesarRN** [ARDroneSDK3/Samples#23]
Hello!

I try to understand iOS example (extract files) for the BeBop drone.

I found "DeviceControllerCompletionBlock" in a lot methods.

What´s means?

Thanks!

**Comment by djavan-bertrand** [comment]
Hi, 

The DeviceControllerCompletionBlock is just an Objective C block that will be called when the acknowledge of the command will be received.
It is defined in DeviceController.h : typedef void (^DeviceControllerCompletionBlock)(void);

Regards, 
Djavan

**Comment by CesarRN** [comment]
Hello djavan-bertrand,
 where is DeviceController.h ?

I only have DeviceControllerWifi, DeviceControllerProtected, ...

I have a lot of problems trying to do a complete app for BeBop from RollingSpider example   :S
I don´t have a lot of classes, for example:  ARThread.

How can "mix" the extract files from FreeFlight 3 into RollingSpider ?

By the other hand, I try to run the Unix example without success
https://github.com/ARDroneSDK3/Samples/issues/22#issuecomment-77870126

I need help   :/

Thanks!!

**Comment by djavan-bertrand** [comment]
DeviceController.h is [here](https://github.com/ARDroneSDK3/Samples/blob/master/iOS/FreeFlight3Extract/DeviceController.h)

If you want to make a connection between a Bebop and an iOS device, I would suggest that you mix RollingSpider iOS example and Bebop Unix sample.

I will try to help you on the Unix sample problem tomorrow.

**Comment by CesarRN** [comment]
Hello djavan-bertrand, I don´t know the reason I didn´t download this file / class ...  ¿?

I want to run with success the Unix sample and then, following the same steps do the same with iOS.

Thanks!

**Comment by CesarRN** [comment]
Hello again.
The class "DeviceController.h" imports #import "ARThread.h" and I don´t have it    :S

Can I replace ARThread objects with  NSThread ? or with ARSAL_Thread?

Thanks!

**Comment by djavan-bertrand** [comment]
Hi the sample is now available. Enjoy !

Djavan
