### ISSUE TITLE
Questions about capturing an image and mass_storage_id 

### ISSUE THREAD

**Issue by dk683** [ARDroneSDK3/Samples#29]
Hello. I am trying to build UNIX program that captures an image from Bebop.
I followed this post (https://github.com/ARDroneSDK3/Samples/issues/14) and found ARCOMMANDS_Generator_GenerateARDrone3MediaRecordPicture. 
I compiled and ran the function, but I could not find where it saved an image. I passed mass_sotrage_id as 1. I am not fully sure whether I am using the function correctly.
Could you tell me an instruction of using ARCOMMANDS_Generator_GenerateARDrone3MediaRecordPicture function and how to find a location where it saved an image? 
I appreciate your help!

Sincerely,

Dong Ki Kim

**Comment by N-Bz** [comment]
Hi,

When you request a picture from the Bebop, the picture is stored in the internal memory. That's the same behavior for video records.

To search and download the media, we provide the libARDataTransfer library (which, basically, is a wrapper around an FTP connection).

You can see a sample for this library [here](https://github.com/ARDroneSDK3/Samples/issues/20). The sample code is for Objective C, but you can make it work with plain C with a few changes.

Regards,
Nicolas.

**Comment by dk683** [comment]
I appreciate your comment! 
I wanted to clarify. I am trying to make a program that shows real-time images, that are taken from flying Bebop, on a computer (Linux).
For this task, would be using libARDataTransfer library the best way?
Thank you for your time!  

Best,
Dong Ki Kim

**Comment by N-Bz** [comment]
Hi,

If you want real time, you should go with the streaming option.
We have a basic sample app for unix [here](https://github.com/ARDroneSDK3/Samples/tree/master/Unix/BebopDroneReceiveStream), which will display the live streaming through mplayer (if installed), that you can use as a base for your application.

The MediaRecordPicture and MediaRecordVideo functions are not suited for real time display.

Regards,
Nicolas.

**Comment by dk683** [comment]
Thank you for your quick reply!
Yes, when I first received Bebop, I looked into the UNIX examples (https://github.com/ARDroneSDK3/Samples/tree/master/Unix) and successfully ran them.
However, I faced with two problems:
1. Somehow streaming quality was not good. I also have ARDrone 2.0. but the streaming quality of Bebop was not better than ARDrone 2.0. I thought this did not make sense because, from my knowledge, Bebop has a better built-in camera than ARDrone 2.0.
2. I could not find C code for taking snapshot of mplayer in real-time. In order to make my application work, I need a real-time image, not a video, but I could not find a way to do it.

Could you give me your advice? Thank you again!

Regards,
Dong Ki Kim

**Comment by dk683** [comment]
For my question #2, this might be not the best solution, but I could use 'S' to continually take a snapshot of mplayer.

**Comment by dk683** [comment]
Would there be any way to receive a real-time image without using mplayer? 
From FreeFlight App source codes, I see many functions that are related to taking a picture (ex. ARCOMMANDS_Generator_GenerateARDrone3MediaRecordPicture). Do they all save an image in the internal memory?

**Comment by djavan-bertrand** [comment]
Yes, taking a picture saves it on the internal memory. 

To get the best streaming quality, be sure to send piloting commands on a regular base (see [this issue](https://github.com/ARDroneSDK3/libARCommands/issues/4) for more information). You should also use a 5Ghz wifi channel.
Best regards, 
Djavan
