### ISSUE TITLE
"JumpingSumoChangePosture" : More then one command dont work

### ISSUE THREAD

**Issue by cromagn** [ARDroneSDK3/Samples#3]
hi all (and really tks for your great SDK),
on unix example Unix "JumpingSumoChangePosture" trying to send two "Piloting Posture" commands one after another, only the first is executed. The only way I've found is to re-initialize the network using ardiscoveryConnect (jsManager) and startNetwork (jsManager) between the two commands but does not seem very smart. can you help me?
Also using "animation"...same effect :(
br
c.
The sequence of "arnetworkCmdCallback" is

[INF] JumpingSumoChangePosture | 19:53:39:821 | main:132 - -- Jumping Sumo Change Posture --
[INF] JumpingSumoChangePosture | 19:53:39:821 | ardiscoveryConnect:218 - - ARDiscovery Connection
[INF] JumpingSumoChangePosture | 19:53:39:842 | startNetwork:250 - - Start ARNetwork
[INF] JumpingSumoChangePosture | 19:53:39:842 | sendPilotingAnimations:195 - - Send Piloting Animations 9
[INF] JumpingSumoChangePosture | 19:53:39:842 | sendPilotingAnimations:199 - Buffer :
[INF] JumpingSumoChangePosture | 19:53:39:842 | sendPilotingAnimations:203 - Esito send Animation command. netError:0 
[INF] JumpingSumoChangePosture | 19:53:39:862 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:39:862 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:39:913 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:39:913 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:39:964 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:39:964 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:40:015 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:40:015 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:40:066 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:2 
[INF] JumpingSumoChangePosture | 19:53:40:066 | arnetworkCmdCallback:412 -  ARNETWORK_MANAGER_CALLBACK_STATUS_TIMEOUT 
[INF] JumpingSumoChangePosture | 19:53:40:066 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:3 
[INF] JumpingSumoChangePosture | 19:53:40:066 | arnetworkCmdCallback:396 -  ARNETWORK_MANAGER_CALLBACK_STATUS_CANCEL 
[INF] JumpingSumoChangePosture | 19:53:40:066 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:5 
[INF] JumpingSumoChangePosture | 19:53:40:066 | arnetworkCmdCallback:400 -  ARNETWORK_MANAGER_CALLBACK_STATUS_DONE 
[INF] JumpingSumoChangePosture | 19:53:40:843 | ardiscoveryConnect:218 - - ARDiscovery Connection
[INF] JumpingSumoChangePosture | 19:53:40:863 | startNetwork:250 - - Start ARNetwork
[INF] JumpingSumoChangePosture | 19:53:40:864 | sendPilotingPosture:364 - - Send Piloting Posture 2
[INF] JumpingSumoChangePosture | 19:53:40:864 | sendPilotingPosture:368 - Buffer :
[INF] JumpingSumoChangePosture | 19:53:40:864 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:40:864 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:40:915 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:40:915 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:40:966 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:40:966 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:41:017 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:0 
[INF] JumpingSumoChangePosture | 19:53:41:017 | arnetworkCmdCallback:408 -  ARNETWORK_MANAGER_CALLBACK_STATUS_SENT 
[INF] JumpingSumoChangePosture | 19:53:41:068 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:2 
[INF] JumpingSumoChangePosture | 19:53:41:068 | arnetworkCmdCallback:412 -  ARNETWORK_MANAGER_CALLBACK_STATUS_TIMEOUT 
[INF] JumpingSumoChangePosture | 19:53:41:068 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:3 
[INF] JumpingSumoChangePosture | 19:53:41:068 | arnetworkCmdCallback:396 -  ARNETWORK_MANAGER_CALLBACK_STATUS_CANCEL 
[INF] JumpingSumoChangePosture | 19:53:41:068 | arnetworkCmdCallback:387 -     - arnetworkCmdCallback 11, cause:5 
[INF] JumpingSumoChangePosture | 19:53:41:068 | arnetworkCmdCallback:400 -  ARNETWORK_MANAGER_CALLBACK_STATUS_DONE 
[INF] JumpingSumoChangePosture | 19:53:41:865 | stopNetwork:319 - - Stop ARNetwork
[INF] JumpingSumoChangePosture | 19:53:42:070 | main:183 - -- END --

**Comment by djavan-bertrand** [comment]
Hi Cromagn, 

The example already shows how to send two commands. One to change the posture in kicker (reversed posture) and the second to change the posture in jumper (normal posture).

As you noticed, there is a sleep between the two commands. This sleep is here to wait that the Jumping changes its posture. Also, there is a sleep at the end to be sure that the last command has enough time to be sent.

I tried to send a lot of changing posture commands, it's working even though some of them are not executed by the jumping (because they are received when it is still in the asked position).

If you still have some trouble sending more than one commands, can you send us the changes you made on the samples ?

Thanks, 
Djavan
