### ISSUE TITLE
Corrupted JPEG File

### ISSUE THREAD

**Issue by dk683** [ARDroneSDK3/Samples#30]
Hello, I referenced Unix JumpiungSumoReceiveStream example (https://github.com/ARDroneSDK3/Samples/tree/master/Unix/JumpingSumoReceiveStream) to write Bebop program that outputs frame images as jpeg files (DISPLAY_WITH_AVPLAY = 0). 
As I ran the code, I did get jpeg files. However, as I opened them, I got the following error message:

"Could not load image 'img_1.jpg'.
Error interpreting JPEG image file (Not a JPEG file: starts with 0x00 0x00).

Could someone help me? Thank you!

**Comment by dk683** [comment]
I was using the below code for saving jpeg images for bebop.
However, from my knowledge, it seems like a frame of jumping sumo is mjpeg and a frame of bebop is h264. Therefore, I think write(frame, frameSize, 1, img); does not work directly. If this is correct, would there be any way to convert h264 to jpeg image real-time?   
```
        case ARSTREAM_READER_CAUSE_FRAME_COMPLETE:
            /* Here, the mjpeg video frame is in the "frame" pointer, with size "frameSize" bytes
             You can do what you want, but keep it as short as possible, as the video is blocked until you return from this callback.
             Typically, you will either copy the frame and return the same buffer to the library, or store the buffer
             in a fifo for pending operations, and provide a new one.
             In this sample, we do nothing and just pass the buffer back*/
            
            ret = jsManager->videoFrame;
            *newBufferCapacity = jsManager->videoFrameSize;
            
            /* Again, don't write files in this thread, that is just for the example :) */
            if (DISPLAY_WITH_FFPLAY)
            {
                // write img files
                fwrite(frame, frameSize, 1, jsManager->video_out);
                fflush (jsManager->video_out);
            }
            else if (jsManager->writeImgs)
            {
                
                char filename[20];
                snprintf(filename, sizeof(filename), "video/img_%d.jpg", jsManager->frameNb);
                
                jsManager->frameNb++;
                FILE *img = fopen(filename, "w");
                fwrite(frame, frameSize, 1, img);
                fclose(img);
            }
```

**Comment by CesarRN** [comment]
Hello dk683

I think we must analyse and decoded the frames.

I don´t have knowledge about media, frames, coded and decoded, ....   :s

You can extract ideas from:
https://developer.apple.com/videos/wwdc/2014/#513

http://i.imgur.com/vMuXlsl.png

http://stackoverflow.com/questions/24884827/possible-locations-for-sequence-picture-parameter-sets-for-h-264-stream


I have the frame into a CMSampleBufferRef and I am loking for a solution to show the CMSampleBufferRef into a VTDecompressionSession or AVSampleBufferDisplayLayer
BUT, I haven´t enough knowledge  :( and I develop the solution very slowly.

If anyone can help us to do this feature will be great!!  :D

Thanks!

**Comment by djavan-bertrand** [comment]
Hi @dk683 

The format of the video stream from the Bebop is not mjeg (like the jumping), it is h264. You can't get a jpg file directly from the stream, you will need to decode the frame as an h264 frame.

Regards, 
Djavan

**Comment by CesarRN** [comment]
Hi djavan-bertrand, do you have any example of decoding a frame as an h264?

We must obtain jpg or mp4 ? 

Thanks!

**Comment by dk683** [comment]
Dear @djavan-bertrand and @CesarRN,

I appreciate your reply! 
@djavan-bertrand. If you don't mind, could I ask for an example code for decoding a h264 frame so that we could save the frame as jpg file? 
Or if you could give us an instruction, that would be very helpful too! 
Thank you for your time, and I hope to hear back from you.

Best,
Dong Ki Kim

**Comment by djavan-bertrand** [comment]
Hi, 
You can maybe check those github projects :
* [openH264](https://github.com/cisco/openh264) (based on custom decoder)
* [iFrameExtractor](https://github.com/lajos/iFrameExtractor) (based on ffmpeg)

Best regards, 
Djavan

**Comment by dk683** [comment]
Just found out that the new sample for decoding is added (https://github.com/ARDroneSDK3/Samples/tree/master/Unix/BebopDroneDecodeStream)! 
Thank you Parrot team! :+1:
