### ISSUE TITLE
Vertical Camera

### ISSUE THREAD

**Issue by Cellendhyll** [ARDroneSDK3/Samples#36]
Is the vertical camera accessible ? Could be to take pictures, form recognition, color tracking... If yes, where do I make the changes between main and vertical camera ?

If not, is that in the roadmap ?

**Comment by djavan-bertrand** [comment]
Hi, 
Which product are you talking about ?
On the RollingSpider you can take pictures with the vertical camera (with a command). On the Bebop, you can't access to the vertical camera as it is used for the hovering and other internal processes.

Regards, 
Djavan

**Comment by Cellendhyll** [comment]
My bad, I was talking about the Bebop. Thanks for your quick answer
