### ISSUE TITLE
Mplayer streaming via mjpeg? 

### ISSUE THREAD

**Issue by dk683** [ARDroneSDK3/Samples#37]
Hello. I am using a Bebop drone to receive video streaming and save the streaming to images. 
As far as I know, the sample code ("BebopDroneReceiveStream.c") uses mplayer to receive the video streaming and the video streaming is encoded by h264. 
As I looked into "JumpingSumoReceiveSteram.c", it uses ffplay for video streaming and video is encoded by mjpeg. 
However, "JumpingSumoReceiveSteram.c" converts the video streaming (frames) to images very easily because it is encoded by mjpeg and saving the images as jpeg.

So I thought if I could use Bebop to do video streaming by mplayer or ffplay and encoded by mjpeg, I can easily convert frames to images. However, as I changed the code 
```
execlp("mplayer", "mplayer", "video_fifo", NULL); 
```
to
```
execlp("ffplay", "ffplay", "-i", "video_fifo", "-f", "mjpeg", NULL);
```
it did not work. 

Is this possible? Thank you!

**Comment by djavan-bertrand** [comment]
Hi, 

That is totally normal. The video from the Bebop is h264 encoded, it is not mjpeg encoded. That is why you can't decode as an mjpeg video flow.

Best regards, 
Djavan

**Comment by dk683** [comment]
Aha! That perfectly makes sense.
Thank you!
