### ISSUE TITLE
Parrot Bepop Drone SDK 3.0 Unix Sample

### ISSUE THREAD

**Issue by vignesh02** [ARDroneSDK3/Samples#9]
Can anyone please share the sample code to control the bepop and video streaming through Unix. The step to connect to another WIFI when the Bepop WIFI is enabled?

**Comment by djavan-bertrand** [comment]
Hi vignesh02,

Now, there is an example which shows you how to connect to a Bebop drone and catch video streaming.
You can merge it with the JumpingSumoPiloting example to get streaming and piloting.

Be sure to read this [closed issue](https://github.com/ARDroneSDK3/Samples/issues/11#issuecomment-73104274) if you have any problem with streaming while sending piloting commands

Regards,
Djavan
